### ISSUE TITLE
Can't update the list

### ISSUE THREAD

**Issue by GenevieveParke** [Samuel-Hoskin/CS-Acronyms#18]
Hi - I've tried to add and correct a couple of items on your spreadsheet, but they don't seem to have been pulled through to the page. Can you tell me what I've done wrong?

Great resource - keep it up.

**Comment by Samuel-Hoskin** [comment]
You are doing nothing wrong. there is an invalid character somewhere in the spreadsheet that causes the code to fail when running so I am trying to figure out how to prevent that from causing an issue and find the current on to remove and get the site working as normal

Thank you for contributing actions, I will try my best to fix this in the time I have

**Comment by Samuel-Hoskin** [comment]
Someone had used a 'NARROW NO-BREAK SPACE', Unicode Character '(U+202F)' Which for some reason python can't interpret. I am going to mark this issue as hopefully unlikely to occur again, but will build a fix if becomes an issue
